# Generated by Django 5.2.11 on 2026-02-27 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('rating', models.FloatField(default=0)),
                ('total_reviews', models.IntegerField(default=0)),
                ('units_sold', models.IntegerField(default=0)),
                ('return_rate', models.FloatField(default=0)),
                ('stock', models.IntegerField(default=0)),
                ('price', models.FloatField()),
                ('mrp', models.FloatField()),
                ('currency', models.CharField(default='Rupee', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductMetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ram', models.CharField(max_length=50, null=True)),
                ('storage', models.CharField(max_length=50, null=True)),
                ('screensize', models.CharField(max_length=50, null=True)),
                ('model', models.CharField(max_length=100, null=True)),
                ('brightness', models.CharField(max_length=50, null=True)),
                ('color', models.CharField(max_length=50, null=True)),
                ('category', models.CharField(max_length=100, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='catalog.product')),
            ],
        ),
    ]
